In [1]:
import numpy as np

In [2]:
a = np.array(43)

In [3]:
type(a)

numpy.ndarray

In [4]:
a.ndim

0

In [5]:
a.shape

()

In [6]:
a.dtype

dtype('int64')

In [7]:
a == 43

True

In [8]:
i = 43

In [9]:
try:
    i.ndim
except Exception as e:
    print(e)

'int' object has no attribute 'ndim'


In [10]:
v = np.array([43])

In [11]:
type(v)

numpy.ndarray

In [12]:
v

array([43])

In [13]:
v.ndim

1

In [14]:
v.shape

(1,)

In [15]:
v = np.arange(10)

In [16]:
v

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [17]:
v.dtype

dtype('int64')

In [18]:
v1 = np.arange(10.5,20.5,0.5)

In [19]:
v1

array([10.5, 11. , 11.5, 12. , 12.5, 13. , 13.5, 14. , 14.5, 15. , 15.5,
       16. , 16.5, 17. , 17.5, 18. , 18.5, 19. , 19.5, 20. ])

In [20]:
v1.dtype

dtype('float64')

In [21]:
v1.size

20

In [22]:
v3 = np.arange(60).reshape(6,10)

In [23]:
v3.shape

(6, 10)

In [24]:
v4 = np.arange(60).reshape(3,4,5)

In [25]:
v4.shape

(3, 4, 5)

In [26]:
la = np.linspace(1,10,10)

In [27]:
la

array([ 1.,  2.,  3.,  4.,  5.,  6.,  7.,  8.,  9., 10.])

In [28]:
la.dtype

dtype('float64')

In [29]:
la2 = np.linspace(1,2,10,retstep=True)

In [30]:
la2

(array([1.        , 1.11111111, 1.22222222, 1.33333333, 1.44444444,
        1.55555556, 1.66666667, 1.77777778, 1.88888889, 2.        ]),
 0.1111111111111111)

In [31]:
la2[0].size

10

In [33]:
la1 = np.linspace(1,10,10,endpoint=False, retstep=True)

In [34]:
la1

(array([1. , 1.9, 2.8, 3.7, 4.6, 5.5, 6.4, 7.3, 8.2, 9.1]), 0.9)

In [35]:
lo = np.logspace(0,2,4)

In [36]:
lo

array([  1.        ,   4.64158883,  21.5443469 , 100.        ])

In [37]:
la2 = np.linspace(0,2,4)

In [38]:
la2

array([0.        , 0.66666667, 1.33333333, 2.        ])

In [39]:
for i in la2 :
    print(np.power(10,i))

1.0
4.641588833612778
21.544346900318832
100.0


In [40]:
v = np.arange(3,5)

In [41]:
v

array([3, 4])

In [42]:
v_p = np.power(v,2)

In [43]:
v_r = np.sqrt(np.sum(v_p))

In [44]:
v_r

5.0

In [45]:
np.hypot(v[0],v[1])

5.0

In [46]:
np.linalg.norm(v)

5.0

In [47]:
e1 = np.array([1,0,0])

In [48]:
np.linalg.norm(e1)

1.0

In [49]:
e2 = np.array([0,1,0])

In [50]:
np.linalg.norm(e2)

1.0

In [51]:
e3 = np.array([0,0,1])

In [52]:
np.linalg.norm(e3)

1.0

In [53]:
v_3 = np.array([1,2,3])

In [55]:
v_3_n = np.linalg.norm(v_3)

In [56]:
v_3_n

3.7416573867739413

In [57]:
v_3_u = v_3 /v_3_n

In [58]:
v_3_u

array([0.26726124, 0.53452248, 0.80178373])

In [60]:
np.linalg.norm(v_3_u)

1.0

In [66]:
def normal(v):
    return v / np.sqrt(np.dot(v,v))

In [67]:
v_4 = np.array([1,2,3,4])

In [68]:
v_4_u = normal(v_4)

In [69]:
v_4_u

array([0.18257419, 0.36514837, 0.54772256, 0.73029674])

In [71]:
np.linalg.norm(v_4_u)

0.9999999999999999

In [72]:
np.round(np.linalg.norm(v_4_u),10)

1.0

In [73]:
a = np.arange(3,5)

In [75]:
b = np.arange(3,5)

In [76]:
np.array_equal(a,b)

True

In [77]:
a_1 = np.linalg.norm(a)

In [78]:
b_1 = np.linalg.norm(b)

In [79]:
a_1 == b_1

True

In [80]:
b_2 = -1*np.linalg.norm(b)

In [82]:
a_1 == b_2

False

In [83]:
c = np.arange(10,13)

In [84]:
d = np.arange(0,3)

In [85]:
np.sqrt(np.sum(np.square(c-d)))

17.320508075688775

In [86]:
np.linalg.norm(c-d)

17.320508075688775

In [87]:
A = np.array([np.array([[43],[44]])])

In [88]:
type(A)

numpy.ndarray

In [89]:
A

array([[[43],
        [44]]])

In [90]:
A.dtype

dtype('int64')

In [91]:
A.ndim

3

In [92]:
A.shape

(1, 2, 1)

In [93]:
shape = (3,4)

In [94]:
dtype = np.int64

In [95]:
B = np.full(shape,7, dtype)

In [96]:
B

array([[7, 7, 7, 7],
       [7, 7, 7, 7],
       [7, 7, 7, 7]])

In [97]:
v1 = np.array([1,2,3,4])

In [98]:
np.linalg.matrix_rank(v1)

1

In [100]:
c = np.array([[1,2,4],[2,4,8]])

In [101]:
c

array([[1, 2, 4],
       [2, 4, 8]])

In [102]:
np.linalg.matrix_rank(c)

1

In [103]:
c1 = np.array([[1,2,4],[2,4,8],[3,4,5]])

In [104]:
np.linalg.matrix_rank(c1)

2

In [105]:
np.linalg.det(c1)

0.0

In [106]:
c1[0]*2 -c1[1]

array([0, 0, 0])

In [107]:
c2 = np.array([[1,3,4],[1,8,5],[2,3,4]])

In [108]:
np.linalg.matrix_rank(c2)

3

In [109]:
np.linalg.det(c2)

-17.0

In [110]:
np.linalg.matrix_rank(c2.T)

3

In [111]:
c3 = np.array([[1,2,3],[4,5,6],[0,0,0]])

In [112]:
c2

array([[1, 3, 4],
       [1, 8, 5],
       [2, 3, 4]])

In [113]:
np.linalg.matrix_rank(c3)

2

In [114]:
np.linalg.det(c3)

0.0

In [115]:
a = np.arange(1,10)

In [116]:
a.sum()

45

In [117]:
np.sum(a)

45

In [118]:
a.sum(axis=0)

45

In [119]:
np.sum(a,axis=0)

45

In [120]:
A = np.array([[2,3],[4,5]])

In [121]:
A.sum()

14

In [122]:
A.sum(axis=0)

array([6, 8])

In [123]:
A.sum(axis=1)

array([5, 9])

In [124]:
C = np.array([[[1,2],[3,4]],
             [[5,6],[7,8]]])

In [125]:
C.ndim

3

In [126]:
C.shape

(2, 2, 2)

In [127]:
C[0]

array([[1, 2],
       [3, 4]])

In [128]:
C[1]

array([[5, 6],
       [7, 8]])

In [129]:
C.sum(axis=0)

array([[ 6,  8],
       [10, 12]])

In [130]:
C.sum(axis=1)

array([[ 4,  6],
       [12, 14]])

In [131]:
C.sum(axis=2)

array([[ 3,  7],
       [11, 15]])

In [132]:
t = np.arange(3*4*2)

In [133]:
t

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23])

In [134]:
t1 = np.reshape(t,(3,4,2))

In [135]:
t1

array([[[ 0,  1],
        [ 2,  3],
        [ 4,  5],
        [ 6,  7]],

       [[ 8,  9],
        [10, 11],
        [12, 13],
        [14, 15]],

       [[16, 17],
        [18, 19],
        [20, 21],
        [22, 23]]])

In [136]:
t1.shape

(3, 4, 2)

In [138]:
t2 = t1.transpose(0,2,1)

In [139]:
t2.shape

(3, 2, 4)

In [140]:
t2

array([[[ 0,  2,  4,  6],
        [ 1,  3,  5,  7]],

       [[ 8, 10, 12, 14],
        [ 9, 11, 13, 15]],

       [[16, 18, 20, 22],
        [17, 19, 21, 23]]])

In [141]:
ra = np.ones((3,4,5,3))

In [142]:
ra.shape

(3, 4, 5, 3)

In [143]:
ra.shape[3]

3

In [144]:
np.rollaxis(ra,3,1).shape

(3, 3, 4, 5)

In [145]:
x = np.array([[1,2,3]])

In [146]:
x.T

array([[1],
       [2],
       [3]])

In [147]:
np.swapaxes(x,0,1)

array([[1],
       [2],
       [3]])

In [148]:
ra.shape

(3, 4, 5, 3)

In [149]:
ra21 = np.swapaxes(ra,2,1)

In [150]:
ra21.shape

(3, 5, 4, 3)

In [151]:
x = np.array([1,2])

In [152]:
x

array([1, 2])

In [154]:
y = np.expand_dims(x, axis=1)

In [155]:
y

array([[1],
       [2]])

In [156]:
z = np.expand_dims(x,axis=0)

In [157]:
z

array([[1, 2]])

In [158]:
x = np.array([[1,4,5],[4,5,6],[7,8,9]])

In [159]:
x

array([[1, 4, 5],
       [4, 5, 6],
       [7, 8, 9]])

In [160]:
x.flatten()

array([1, 4, 5, 4, 5, 6, 7, 8, 9])

In [161]:
x.ravel()

array([1, 4, 5, 4, 5, 6, 7, 8, 9])

In [162]:
np.may_share_memory(x.flatten(),x)

False

In [163]:
np.may_share_memory(x.ravel(),x)

True

In [164]:
a = np.array([[1,2,3],[4,5,6],[7,8,8]])

In [165]:
a

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 8]])

In [166]:
a.shape

(3, 3)

In [167]:
np.trace(a)

14

In [168]:
a.trace()

14

In [169]:
b = np.array([[1,0,0], [0,3,0],[0,0,5]])

In [170]:
b

array([[1, 0, 0],
       [0, 3, 0],
       [0, 0, 5]])

In [172]:
b.diagonal()

array([1, 3, 5])

In [173]:
np.diagonal(b)

array([1, 3, 5])

In [174]:
c = np.diag(np.arange(1,4))

In [175]:
c

array([[1, 0, 0],
       [0, 2, 0],
       [0, 0, 3]])

In [176]:
d = np.diag(np.arange(1,4),k=1)

In [177]:
d

array([[0, 1, 0, 0],
       [0, 0, 2, 0],
       [0, 0, 0, 3],
       [0, 0, 0, 0]])

In [178]:
e = np.diag(np.arange(1,4), k=-1)

In [179]:
e

array([[0, 0, 0, 0],
       [1, 0, 0, 0],
       [0, 2, 0, 0],
       [0, 0, 3, 0]])

In [180]:
f = np.diag([[1,2],[3,4]])

In [181]:
f

array([1, 4])

In [182]:
g = np.diagonal([[1,2],[3,4]])

In [183]:
g

array([1, 4])

In [184]:
h = np.eye(3,3)

In [185]:
h

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [187]:
i = np.eye(3,3,k= 1)

In [188]:
i

array([[0., 1., 0.],
       [0., 0., 1.],
       [0., 0., 0.]])

In [189]:
j = np.eye(3,3,k=-1)

In [190]:
j

array([[0., 0., 0.],
       [1., 0., 0.],
       [0., 1., 0.]])

In [191]:
k = np.diag([4,4,4])

In [192]:
k

array([[4, 0, 0],
       [0, 4, 0],
       [0, 0, 4]])

In [193]:
k*1/4

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [194]:
l = np.identity(3)

In [195]:
l

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [196]:
s = np.arange(1,10).reshape(3,3)

In [197]:
s

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [198]:
s.dot(1)

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [199]:
a = np.arange(1,10).reshape(3,3)

In [200]:
a

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [201]:
np.tril(a)

array([[1, 0, 0],
       [4, 5, 0],
       [7, 8, 9]])

In [202]:
np.tril(a,k=-1)

array([[0, 0, 0],
       [4, 0, 0],
       [7, 8, 0]])

In [203]:
b = np.arange(1,10).reshape(3,3)

In [204]:
b

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [206]:
np.triu(b)

array([[1, 2, 3],
       [0, 5, 6],
       [0, 0, 9]])

In [207]:
np.triu(b,k=1)

array([[0, 2, 3],
       [0, 0, 6],
       [0, 0, 0]])

In [208]:
c = np.triu(b)

In [209]:
c

array([[1, 2, 3],
       [0, 5, 6],
       [0, 0, 9]])

In [210]:
c.T

array([[1, 0, 0],
       [2, 5, 0],
       [3, 6, 9]])

In [211]:
d = np.tril(b)

In [212]:
d.T

array([[1, 4, 7],
       [0, 5, 8],
       [0, 0, 9]])

In [213]:
d * d

array([[ 1,  0,  0],
       [16, 25,  0],
       [49, 64, 81]])

In [214]:
c*c

array([[ 1,  4,  9],
       [ 0, 25, 36],
       [ 0,  0, 81]])

In [215]:
d*c

array([[ 1,  0,  0],
       [ 0, 25,  0],
       [ 0,  0, 81]])

In [216]:
z = np.zeros((3,3))

In [217]:
z

array([[0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.]])

In [218]:
z0 = np.zeros(3)

In [219]:
z0

array([0., 0., 0.])

In [220]:
z1 = np.zeros_like(np.arange(1,10).reshape(3,3))

In [221]:
z1

array([[0, 0, 0],
       [0, 0, 0],
       [0, 0, 0]])

In [222]:
e = np.empty(3)

In [223]:
e

array([0., 0., 0.])

In [224]:
e33 = np.empty((3,3))

In [225]:
e33

array([[4.9e-324, 9.9e-324, 1.5e-323],
       [2.0e-323, 2.5e-323, 3.0e-323],
       [3.5e-323, 4.0e-323, 4.4e-323]])

In [226]:
X = np.array([[1,2,3],[2,3,5],[3,5,6]])

In [227]:
X

array([[1, 2, 3],
       [2, 3, 5],
       [3, 5, 6]])

In [228]:
X.T

array([[1, 2, 3],
       [2, 3, 5],
       [3, 5, 6]])

In [229]:
np.array_equal(X,X.T)

True

In [230]:
np.array_equiv(X,X.T)

True

In [231]:
X + X.T

array([[ 2,  4,  6],
       [ 4,  6, 10],
       [ 6, 10, 12]])

In [232]:
np.dot(X,X.T)

array([[14, 23, 31],
       [23, 38, 51],
       [31, 51, 70]])

In [234]:
a = np.transpose(np.dot(X,X.T))

In [235]:
b = np.dot(X.T,X)

In [236]:
a == b

array([[ True,  True,  True],
       [ True,  True,  True],
       [ True,  True,  True]])

In [237]:
Y = np.array([[0,2,-3],[-2,0,5],[3,-5,0]])

In [238]:
Y

array([[ 0,  2, -3],
       [-2,  0,  5],
       [ 3, -5,  0]])

In [239]:
Y + Y.T

array([[0, 0, 0],
       [0, 0, 0],
       [0, 0, 0]])

In [240]:
Y.T == -Y

array([[ True,  True,  True],
       [ True,  True,  True],
       [ True,  True,  True]])

In [241]:
Y - Y.T

array([[  0,   4,  -6],
       [ -4,   0,  10],
       [  6, -10,   0]])

In [242]:
np.dot(Y,Y.T)

array([[ 13, -15, -10],
       [-15,  29,  -6],
       [-10,  -6,  34]])

In [243]:
np.dot(Y.T,Y)

array([[ 13, -15, -10],
       [-15,  29,  -6],
       [-10,  -6,  34]])

In [244]:
a = np.arange(1,10).reshape(3,3)

In [245]:
a

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [246]:
b = np.eye(3,dtype='int')

In [247]:
b

array([[1, 0, 0],
       [0, 1, 0],
       [0, 0, 1]])

In [248]:
c = np.array([[0,1,0],[1,0,0],[0,0,1]])

In [249]:
np.dot(a,c)

array([[2, 1, 3],
       [5, 4, 6],
       [8, 7, 9]])

In [250]:
from scipy.stats import ortho_group

In [251]:
x = ortho_group.rvs(3)

In [252]:
x

array([[ 0.57257332,  0.43037788,  0.69780704],
       [-0.79254282,  0.07270318,  0.60546686],
       [-0.20984675,  0.89971614, -0.3827208 ]])

In [253]:
i3 = np.dot(x,x.T)

In [254]:
i3

array([[ 1.00000000e+00,  3.27344201e-16, -2.15764832e-16],
       [ 3.27344201e-16,  1.00000000e+00, -7.51430397e-17],
       [-2.15764832e-16, -7.51430397e-17,  1.00000000e+00]])

In [255]:
c = np.eye(3)

In [257]:
np.allclose(c,i3)

True

In [258]:
np.fabs(np.linalg.det(x))

1.0000000000000007

In [259]:
a = np.array([[1,2],[3,4]])

In [260]:
a

array([[1, 2],
       [3, 4]])

In [261]:
a.T

array([[1, 3],
       [2, 4]])

In [262]:
a.transpose()

array([[1, 3],
       [2, 4]])

In [263]:
np.transpose(a)

array([[1, 3],
       [2, 4]])