In [1]:
import numpy as np

In [2]:
a = np.zeros((5,5), dtype=np.int_)

In [3]:
a.shape

(5, 5)

In [4]:
a

array([[0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0]])

In [5]:
a != 0

array([[False, False, False, False, False],
       [False, False, False, False, False],
       [False, False, False, False, False],
       [False, False, False, False, False],
       [False, False, False, False, False]])

In [6]:
(a != 0).any()

False

In [7]:
np.any(a !=0)

False

In [8]:
(a != 0).any

<function ndarray.any>

In [9]:
np.any

<function numpy.any(a, axis=None, out=None, keepdims=<no value>)>

In [10]:
np.ndarray.any is np.core.fromnumeric.any

False

In [11]:
help(np.ndarray.any)

Help on method_descriptor:

any(...)
    a.any(axis=None, out=None, keepdims=False)
    
    Returns True if any of the elements of `a` evaluate to True.
    
    Refer to `numpy.any` for full documentation.
    
    See Also
    --------
    numpy.any : equivalent function



In [12]:
help(a.any)

Help on built-in function any:

any(...) method of numpy.ndarray instance
    a.any(axis=None, out=None, keepdims=False)
    
    Returns True if any of the elements of `a` evaluate to True.
    
    Refer to `numpy.any` for full documentation.
    
    See Also
    --------
    numpy.any : equivalent function



In [13]:
np_ = set(dir(np))

In [14]:
nd_ = set(dir(np.ndarray))

In [16]:
npd_ =np_ & nd_

In [17]:
len(npd_)

48

In [18]:
count = 0
for i in list(npd_):
    count +=1
    print(i, end=" ")
    if count % 5 == 0:
        print()

nbytes nonzero size __doc__ argsort 
cumprod real squeeze transpose copy 
mean sort searchsorted resize argmin 
dot ndim argmax clip shape 
conjugate diagonal dtype compress trace 
ravel all conj __dir__ any 
max sum swapaxes reshape round 
take var partition cumsum argpartition 
ptp imag prod min put 
choose repeat std 

In [19]:
a = dir(np)

In [20]:
np.ufunc

numpy.ufunc

In [21]:
count = 0
for i in a :
    if i == "Tester":
        continue
    if type(np.__dict__[i]) ==np.ufunc  :
        print(i, end=" ")
        count += 1
        if count % 5 == 0:
            print()

abs absolute add arccos arccosh 
arcsin arcsinh arctan arctan2 arctanh 
bitwise_and bitwise_not bitwise_or bitwise_xor cbrt 
ceil conj conjugate copysign cos 
cosh deg2rad degrees divide divmod 
equal exp exp2 expm1 fabs 
float_power floor floor_divide fmax fmin 
fmod frexp gcd greater greater_equal 
heaviside hypot invert isfinite isinf 
isnan isnat lcm ldexp left_shift 
less less_equal log log10 log1p 
log2 logaddexp logaddexp2 logical_and logical_not 
logical_or logical_xor matmul maximum minimum 
mod modf multiply negative nextafter 
not_equal positive power rad2deg radians 
reciprocal remainder right_shift rint sign 
signbit sin sinh spacing sqrt 
square subtract tan tanh 

KeyError: 'testing'

In [22]:
import types

In [23]:
count = 0
for i in a :
    if i == "Tester" :
        continue
    if type(np.__dict__[i]
           count += 1    ) == types.FunctionType  :
    print(count)

SyntaxError: invalid syntax (<ipython-input-23-c7f7160058cf>, line 6)

In [24]:
type(np.add)

numpy.ufunc

In [25]:
type(np.sort)

function

In [26]:
set(dir(np.add)) - set(dir(np.sort))

{'accumulate',
 'at',
 'identity',
 'nargs',
 'nin',
 'nout',
 'ntypes',
 'outer',
 'reduce',
 'reduceat',
 'signature',
 'types'}

In [27]:
a = np.array([1,2,3,4])

In [28]:
np.add(a,a)

array([2, 4, 6, 8])

In [29]:
np.add.accumulate(a)

array([ 1,  3,  6, 10])

In [30]:
a = np.arange(6,10)

In [31]:
a

array([6, 7, 8, 9])

In [33]:
b = np.arange(10,14)

In [34]:
b

array([10, 11, 12, 13])

In [35]:
c = a* b

In [36]:
c

array([ 60,  77,  96, 117])

In [37]:
d = a[:, np.newaxis]

In [38]:
d

array([[6],
       [7],
       [8],
       [9]])

In [39]:
d.shape

(4, 1)

In [40]:
e = b[np.newaxis,:]

In [41]:
e

array([[10, 11, 12, 13]])

In [42]:
e.shape

(1, 4)

In [43]:
f = d @ e

In [44]:
f

array([[ 60,  66,  72,  78],
       [ 70,  77,  84,  91],
       [ 80,  88,  96, 104],
       [ 90,  99, 108, 117]])

In [45]:
a2 = np.array([1,2,3,4])

In [46]:
a2

array([1, 2, 3, 4])

In [47]:
a2 = a2.reshape(2,2)

In [48]:
a2

array([[1, 2],
       [3, 4]])

In [49]:
np.sum(a2)

10

In [50]:
np.sum(a2, axis=0)

array([4, 6])

In [51]:
np.sum(a2,axis=1)

array([3, 7])

In [52]:
a3 = np.arange(1,9)

In [53]:
a3

array([1, 2, 3, 4, 5, 6, 7, 8])

In [54]:
a3 = a3.reshape(2,2,2)

In [56]:
a3

array([[[1, 2],
        [3, 4]],

       [[5, 6],
        [7, 8]]])

In [57]:
a3.shape

(2, 2, 2)

In [58]:
a3[0]

array([[1, 2],
       [3, 4]])

In [59]:
a3[1]

array([[5, 6],
       [7, 8]])

In [60]:
np.sum(a3)

36

In [61]:
np.sum(a3, axis=0)

array([[ 6,  8],
       [10, 12]])

In [62]:
np.sum(a3, axis=1)

array([[ 4,  6],
       [12, 14]])

In [63]:
np.sum(a3, axis=2)

array([[ 3,  7],
       [11, 15]])

In [64]:
a = np.array([4,5])

In [65]:
a.shape

(2,)

In [69]:
a

array([4, 5])

In [66]:
b = np.array([3,4,6])

In [67]:
b.shape

(3,)

In [68]:
b

array([3, 4, 6])

In [70]:
try:
    a+b
except Exception as e :
    print(e)

operands could not be broadcast together with shapes (2,) (3,) 


In [71]:
a = np.append(a,[6])

In [73]:
a.shape

(3,)

In [74]:
a+b

array([ 7,  9, 12])

In [75]:
a2 = np.array([[1,2,3],[3,4,5]])

In [76]:
b2 = np.array([1,2])

In [77]:
try:
    a2 + b2
except Exception as e:
    print(e)

operands could not be broadcast together with shapes (2,3) (2,) 


In [78]:
b2 = np.append(b2,[3])

In [79]:
b2.shape

(3,)

In [80]:
a2 + b2

array([[2, 4, 6],
       [4, 6, 8]])

In [81]:
a = np.array([[1,2],[3,4]])

In [82]:
a

array([[1, 2],
       [3, 4]])

In [83]:
b = a

In [84]:
b

array([[1, 2],
       [3, 4]])

In [85]:
a is b

True

In [86]:
a is b.base

False

In [87]:
b[0] = 999

In [88]:
a

array([[999, 999],
       [  3,   4]])

In [89]:
b

array([[999, 999],
       [  3,   4]])

In [90]:
f = np.array([4,5,6,7,8])

In [91]:
e = f.copy()

In [92]:
e.base is None

True

In [93]:
g = f[:]
g.base

array([4, 5, 6, 7, 8])

In [94]:
g.base is f

True

In [95]:
np.may_share_memory(g,f)

True

In [96]:
g[1] =99999

In [97]:
g

array([    4, 99999,     6,     7,     8])

In [98]:
f

array([    4, 99999,     6,     7,     8])

In [99]:
h = f.view()

In [100]:
h

array([    4, 99999,     6,     7,     8])

In [101]:
h.base is f

True

In [102]:
np.may_share_memory(h,f)

True

In [103]:
a = np.array([1,3,5,7])

In [104]:
b = np.array(a,copy=True)

In [105]:
b.base is None

True

In [106]:
c = np.array(a)

In [107]:
c.base is None

True

In [108]:
aa = np.array([1,2,3,4,5,6,7])

In [109]:
aa_c = np.sort(aa, axis=0)

In [110]:
aa_c

array([1, 2, 3, 4, 5, 6, 7])

In [111]:
aa_c.base is None

True

In [112]:
aa[6]

7

In [113]:
aa.sort()

In [114]:
aa

array([1, 2, 3, 4, 5, 6, 7])

In [115]:
l = list(range(1,10))

In [116]:
l

[1, 2, 3, 4, 5, 6, 7, 8, 9]

In [117]:
index = 1

In [118]:
l.__getitem__(index)

2

In [119]:
index = slice(1,3)

In [120]:
l.__getitem__(index)

[2, 3]

In [121]:
a = np.array([1,2,3,4,5,6,7])

In [122]:
index = 1

In [125]:
a.__getitem__(index)

2

In [126]:
a.__getitem__(index)

2

In [127]:
index = 1

In [128]:
a.__getitem__(index)

2

In [129]:
index=[1]

In [130]:
a.__getitem__(index)

array([2])

In [131]:
index = a<4

In [132]:
index

array([ True,  True,  True, False, False, False, False])

In [133]:
a.__getitem__(index)

array([1, 2, 3])

In [134]:
index = a<3

In [135]:
a.__setitem__(index , 9080)

In [136]:
a

array([9080, 9080,    3,    4,    5,    6,    7])