In [1]:
import numpy as np

In [2]:
a = np.array([[1,2],[3,4]])

In [3]:
np.linalg.det(a)

-2.0000000000000004

In [4]:
b = np.array([[3,4],[1,2]])

In [5]:
np.linalg.det(a)

-2.0000000000000004

In [6]:
ai = np.linalg.inv(a)

In [8]:
bi = np.linalg.inv(b)

In [9]:
ab = np.linalg.inv(np.dot(a,b))

In [10]:
ba = np.dot(bi,ai)

In [11]:
np.allclose(ab,ba)

True

In [12]:
a

array([[1, 2],
       [3, 4]])

In [13]:
b

array([[3, 4],
       [1, 2]])

In [14]:
c = np.dot(a,b)

In [15]:
bi

array([[ 1. , -2. ],
       [-0.5,  1.5]])

In [16]:
ai

array([[-2. ,  1. ],
       [ 1.5, -0.5]])

In [17]:
d = np.dot(bi,ai)

In [18]:
e = np.dot(c,d)

In [19]:
e

array([[1.0000000e+00, 0.0000000e+00],
       [1.0658141e-14, 1.0000000e+00]])

In [20]:
ma = np.arange(1,10).reshape(3,3)

In [21]:
ma

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [22]:
list(range(0))

[]

In [23]:
a = np.array(list(range(0))+list(range(1,3)))[:,np.newaxis]

In [24]:
a

array([[1],
       [2]])

In [25]:
b = np.array(list(range(0))+list(range(1,3)))

In [26]:
b

array([1, 2])

In [27]:
ja = ma[a,b]

In [28]:
ja

array([[5, 6],
       [8, 9]])

In [29]:
np.linalg.det(ja)

-2.9999999999999996

In [30]:
cofactor = (-1)**(0+0) *np.linalg.det(ja)

In [31]:
cofactor

-2.9999999999999996

In [32]:
a = np.ones((3,3))

In [33]:
np.linalg.det(a)

0.0

In [34]:
np.linalg.pinv(a)

array([[0.11111111, 0.11111111, 0.11111111],
       [0.11111111, 0.11111111, 0.11111111],
       [0.11111111, 0.11111111, 0.11111111]])

In [36]:
try:
    np.linalg.inv(a)
except Exception as e:
    print(e)

Singular matrix


In [37]:
# Tensordot 연산 확인하기

In [38]:
x = np.random.randint(1,10,(2,2))

In [39]:
x

array([[4, 6],
       [1, 8]])

In [40]:
y = np.random.randint(1,10,(2,2))

In [41]:
y

array([[3, 5],
       [9, 1]])

In [42]:
np.dot(x,y)

array([[66, 26],
       [75, 13]])

In [43]:
np.tensordot(x,y, axes=1)

array([[66, 26],
       [75, 13]])

In [44]:
np.inner(x,y)

array([[42, 42],
       [43, 17]])

In [45]:
np.tensordot(x,y, axes=(-1,-1))

array([[42, 42],
       [43, 17]])

In [46]:
x = np.random.randint(1,10,(2,2))

In [47]:
x

array([[3, 2],
       [5, 3]])

In [49]:
y = np.random.randint(1,10,(2,2))

In [50]:
y

array([[2, 2],
       [3, 9]])

In [51]:
a = np.tensordot(x,y, axes=0)

In [52]:
a = np.tensordot(x,y,axes=0)

In [53]:
a.shape

(2, 2, 2, 2)

In [54]:
a

array([[[[ 6,  6],
         [ 9, 27]],

        [[ 4,  4],
         [ 6, 18]]],


       [[[10, 10],
         [15, 45]],

        [[ 6,  6],
         [ 9, 27]]]])

In [55]:
x = np.random.randint(1,10,(2,2))

In [56]:
x

array([[2, 5],
       [2, 9]])

In [57]:
y = np.random.randint(1,10,(2,2))

In [58]:
y

array([[5, 3],
       [7, 9]])

In [59]:
a = np.tensordot(x,y,axes=2)

In [60]:
a.shape

()

In [61]:
a

array(120)

In [62]:
c = np.random.randint(1,10,(2,2,2))

In [63]:
c

array([[[6, 8],
        [3, 6]],

       [[3, 9],
        [2, 9]]])

In [64]:
d = np.random.randint(1,10,(2,2,2))

In [65]:
d

array([[[7, 5],
        [2, 9]],

       [[1, 4],
        [4, 3]]])

In [66]:
np.dot(c.reshape(2,4),d.reshape(4,2))

array([[ 85, 132],
       [ 77, 131]])

In [67]:
b = np.tensordot(c,d,axes=2)

In [68]:
b

array([[ 85, 132],
       [ 77, 131]])

In [69]:
#kron 연산 처리하기

In [70]:
ll = np.arange(1,4)

In [71]:
ls = np.array([10,20,30])

In [72]:
np.kron(ll,ls)

array([10, 20, 30, 20, 40, 60, 30, 60, 90])

In [82]:
ll_ = np.repeat(ll,3)

In [83]:
ll_

array([1, 1, 1, 2, 2, 2, 3, 3, 3])

In [84]:
ls_ = np.tile(ls,3)

In [85]:
ls_

array([10, 20, 30, 10, 20, 30, 10, 20, 30])

In [86]:
ll_ * ls_

array([10, 20, 30, 20, 40, 60, 30, 60, 90])

In [87]:
np.outer(ll,ls)

array([[10, 20, 30],
       [20, 40, 60],
       [30, 60, 90]])

In [88]:
x = np.array([1,2,3,4]).reshape(2,2)

In [89]:
x

array([[1, 2],
       [3, 4]])

In [90]:
x = np.array([1,2,3,4]).reshape(2,2)

In [91]:
x

array([[1, 2],
       [3, 4]])

In [92]:
y = np.eye(2)

In [93]:
y

array([[1., 0.],
       [0., 1.]])

In [94]:
np.kron(x,y)

array([[1., 0., 2., 0.],
       [0., 1., 0., 2.],
       [3., 0., 4., 0.],
       [0., 3., 0., 4.]])

In [95]:
x_ = np.repeat(x,2, axis=0)

In [96]:
x_

array([[1, 2],
       [1, 2],
       [3, 4],
       [3, 4]])

In [97]:
x_ = np.repeat(x_,2,axis=1)

In [98]:
x_

array([[1, 1, 2, 2],
       [1, 1, 2, 2],
       [3, 3, 4, 4],
       [3, 3, 4, 4]])

In [99]:
y_ = np.tile(y,(2,2))

In [100]:
y_

array([[1., 0., 1., 0.],
       [0., 1., 0., 1.],
       [1., 0., 1., 0.],
       [0., 1., 0., 1.]])

In [101]:
np.multiply(x_,y_)

array([[1., 0., 2., 0.],
       [0., 1., 0., 2.],
       [3., 0., 4., 0.],
       [0., 3., 0., 4.]])

In [102]:
x.reshape(4,1)

array([[1],
       [2],
       [3],
       [4]])

In [103]:
y.reshape(1,4)

array([[1., 0., 0., 1.]])

In [104]:
np.outer(x,y)

array([[1., 0., 0., 1.],
       [2., 0., 0., 2.],
       [3., 0., 0., 3.],
       [4., 0., 0., 4.]])

In [105]:
np.dot(x.reshape(4,1), y.reshape(1,4))

array([[1., 0., 0., 1.],
       [2., 0., 0., 2.],
       [3., 0., 0., 3.],
       [4., 0., 0., 4.]])

In [111]:
A = np.array([[1,2,3],[4,5,6]])

In [112]:
A

array([[1, 2, 3],
       [4, 5, 6]])

In [113]:
A.T

array([[1, 4],
       [2, 5],
       [3, 6]])

In [115]:
np.einsum("ij->ji", A)

array([[1, 4],
       [2, 5],
       [3, 6]])

In [116]:
AA = np.arange(10)

In [117]:
np.einsum('i->',AA)

45

In [120]:
np.sum(AA)

45

In [121]:
A__ = np.array([[1,1,1],[3,2,4],[7,5,8]])

In [123]:
np.einsum("ij->", A__)

32

In [124]:
np.sum(A__, axis=1)

array([ 3,  9, 20])

In [125]:
np.einsum("ij->j",A__)

array([11,  8, 13])

In [127]:
np.einsum("ij->J",A__)

ValueError: einstein sum subscripts string included output subscript 'J' which never appeared in an input