In [1]:
import numpy as np
import pandas as pd

In [2]:
type(np.mgrid)

numpy.lib.index_tricks.MGridClass

In [3]:
np.mgrid.__class__

numpy.lib.index_tricks.MGridClass

In [4]:
np.arange(10,30,10)

array([10, 20])

In [5]:
np.arange(1,5)

array([1, 2, 3, 4])

In [6]:
np.broadcast_arrays(np.arange(10,30,10).reshape(2,1),
                   np.arange(1,5).reshape(1,4))

[array([[10, 10, 10, 10],
        [20, 20, 20, 20]]),
 array([[1, 2, 3, 4],
        [1, 2, 3, 4]])]

In [7]:
a, b = np.mgrid[10:30:10,1:5]

In [8]:
a

array([[10, 10, 10, 10],
       [20, 20, 20, 20]])

In [9]:
b

array([[1, 2, 3, 4],
       [1, 2, 3, 4]])

In [10]:
s1 = slice(10,30,10)

In [11]:
s2 = slice(1,5)

In [13]:
a_,b_ = np.mgrid[s1, s2]

In [14]:
a_

array([[10, 10, 10, 10],
       [20, 20, 20, 20]])

In [15]:
b_

array([[1, 2, 3, 4],
       [1, 2, 3, 4]])

In [16]:
type(np.ogrid)

numpy.lib.index_tricks.OGridClass

In [17]:
c,d = np.ogrid[10:30:10, 1:5]

In [18]:
c

array([[10],
       [20]])

In [19]:
d

array([[1, 2, 3, 4]])

In [20]:
e, f = np.broadcast_arrays(c,d)

In [21]:
e

array([[10, 10, 10, 10],
       [20, 20, 20, 20]])

In [22]:
f

array([[1, 2, 3, 4],
       [1, 2, 3, 4]])

In [23]:
a = np.array([[1,3],[2,5],[3,7]])

In [24]:
a

array([[1, 3],
       [2, 5],
       [3, 7]])

In [25]:
np.compress([0,1],a)

array([3])

In [26]:
a[[0],[1]]

array([3])

In [27]:
np.compress([0,1,1,0,0,0],a)

array([3, 2])

In [28]:
np.compress([0,1,0],a,axis=0)

array([[2, 5]])

In [29]:
np.compress([0,1],a,axis=1)

array([[3],
       [5],
       [7]])

In [30]:
cond = np.mod(a,3)

In [31]:
cond

array([[1, 0],
       [2, 2],
       [0, 1]])

In [32]:
np.extract(cond,a)

array([1, 2, 5, 7])

In [33]:
cc = np.array([[1,0],[1,1],[0,1]])

In [34]:
np.extract(cc,a)

array([1, 2, 5, 7])

In [35]:
x = np.array([[[0], [1], [2]]])

In [36]:
x

array([[[0],
        [1],
        [2]]])

In [37]:
x.shape

(1, 3, 1)

In [38]:
np.squeeze(x)

array([0, 1, 2])

In [39]:
np.squeeze(x,axis=0)

array([[0],
       [1],
       [2]])

In [41]:
np.squeeze(x,axis=2)

array([[0, 1, 2]])

In [42]:
y = np.array([[0],[1]])

In [43]:
y.shape

(2, 1)

In [44]:
np.squeeze(y,1)

array([0, 1])

In [45]:
z = np.array([[0,2],[1,3]])

In [46]:
np.squeeze(z)

array([[0, 2],
       [1, 3]])

In [48]:
try:
    np.squeeze(z,1)
except Exception as e:
    print(e)

cannot select an axis to squeeze out which has size not equal to one


In [49]:
# 배열 내의 원소 반복하기

In [50]:
a = np.linspace(1,5,5, dtype=np.int32)

In [51]:
a

array([1, 2, 3, 4, 5], dtype=int32)

In [52]:
np.repeat(a,2)

array([1, 1, 2, 2, 3, 3, 4, 4, 5, 5], dtype=int32)

In [54]:
np.repeat(a,[2,2,2,2,2])

array([1, 1, 2, 2, 3, 3, 4, 4, 5, 5], dtype=int32)

In [55]:
np.repeat(a,[2,0,0,0,0])

array([1, 1], dtype=int32)

In [57]:
b = np.linspace(1,4,4, dtype=np.int32).reshape(2,2)

In [58]:
b

array([[1, 2],
       [3, 4]], dtype=int32)

In [59]:
np.repeat(b,2, axis=0)

array([[1, 2],
       [1, 2],
       [3, 4],
       [3, 4]], dtype=int32)

In [60]:
np.repeat(b,2, axis=1)

array([[1, 1, 2, 2],
       [3, 3, 4, 4]], dtype=int32)

In [61]:
np.repeat(b,[2,3], axis=0)

array([[1, 2],
       [1, 2],
       [3, 4],
       [3, 4],
       [3, 4]], dtype=int32)

In [62]:
np.repeat(b, [2,3], axis=1)

array([[1, 1, 2, 2, 2],
       [3, 3, 4, 4, 4]], dtype=int32)

In [63]:
e = np.arange(4).reshape(2,2)

In [64]:
e

array([[0, 1],
       [2, 3]])

In [65]:
np.tile(e,2)

array([[0, 1, 0, 1],
       [2, 3, 2, 3]])

In [66]:
np.tile(e,[2,2])

array([[0, 1, 0, 1],
       [2, 3, 2, 3],
       [0, 1, 0, 1],
       [2, 3, 2, 3]])

In [67]:
np.tile(e,[2,2,2])

array([[[0, 1, 0, 1],
        [2, 3, 2, 3],
        [0, 1, 0, 1],
        [2, 3, 2, 3]],

       [[0, 1, 0, 1],
        [2, 3, 2, 3],
        [0, 1, 0, 1],
        [2, 3, 2, 3]]])

In [68]:
a = np.linspace(1,6,6, dtype=np.int32).reshape(2,3)

In [70]:
a

array([[1, 2, 3],
       [4, 5, 6]], dtype=int32)

In [71]:
b = np.linspace(7,13,6, dtype=np.int32).reshape(2,3)

In [72]:
b

array([[ 7,  8,  9],
       [10, 11, 13]], dtype=int32)

In [73]:
np.concatenate([a,b])

array([[ 1,  2,  3],
       [ 4,  5,  6],
       [ 7,  8,  9],
       [10, 11, 13]], dtype=int32)

In [74]:
np.concatenate([a,b], axis=0)

array([[ 1,  2,  3],
       [ 4,  5,  6],
       [ 7,  8,  9],
       [10, 11, 13]], dtype=int32)